[Feat] 하루기록 생성, 하루기록 조회, 부작용 생성, 부작용 조회 구현
FOREGG-DEV/FOREGG_Android pull request #54
Opened 2024-05-25 20:32 UTC by dogmania

close #47

2024-05-25 23:59 UTC, rudtjr1106 requested changes
코드가 너무 깔끔해졌습니다! 다만 일부 코드에서 좀 더 좋은 방법이 있는 것 같아 코멘트 남겼습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on data/src/main/java/com/foregg/data/dto/dailyRecord/SideEffectResponseListItem.kt
> +data class SideEffectResponseListItem(
만약의 경우를 대비하여 기본값 추가해주시면 좋을 것 같습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
> +            customTabBar.leftTab.setOnClickListener {
요거 setOnClickListener 안쓰셔도 됩니다! 그냥 custimTabBar.leftBrnClicked만 쓰시면 될 것 같습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/adapter/DailyRecordViewHolder.kt
> +        binding.apply {
when문의 내용이 조금 길다보니 가시성이 약간 떨어질 것 같습니다!
함수화 시켜 분리하는건 어떨까요??

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordFragment.kt
> +    private fun getEditTextContent() {
editText를 viewModel에서 바로 사용할 수 있습니다! 해당 내용은 ViewModel에 적어두겠습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
> +    fun onClickBtnWorst() {
각각의 이모지의 boolean 값을 설정하기보다 type으로 사용하면 어떨까요??
예를들어
`isSelectEmotionStateFlow : MutableStateFlow<이모지타입> = MutableStateFlow(이모지타입 기본)`
이렇게 설정하고 클릭되면 
`isSelectEmotionStateFlow.update { 클릭된 이모지 타입 }`
요렇게 바꾸면 코드가 엄청 줄어들 것 같습니다!

xml에서는
src = "@{vm.uiState.isSelectEmotion == 각 이모지의 맞는 타입 ? 클릭된 이미지 : 흑백 이미지}"
이렇게 사용할 수 있습니다!

원래 메인 바텀네비게이션 이동 방식도 이렇게 했는데 저도 위 방식이 간결한 것 같아 수정했습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
> +    fun onClickBtnNext() {
editText도 pageState에서 관리하면 간편합니다!
다만 이 방법은 two-line 바인딩이라 editText의 변수를 var로 관리해야 합니다!
예시
```
data class CreateDailyRecordPageState (
    var 변수명 : MutableStateFlow<String>
): PageState
```
이렇게 선언하고 editText를 사용하는 xml에서 다음과 같이 적용하면 viewModel에서 실시간으로 변하는 editText의 내용을 갖고 있을 수 있습니다!
xml
```
<EditText
    ~~
    text="@={vm.uiState.변수명}"
```

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
> +        val trueEmotion = emotionStateFlows.firstOrNull { it.first.value }
만약 isSelectEmotion으로 관리한다면 위 코드들은 사라질 수 있을 것 같습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createSideEffect/CreateSideEffectFragment.kt
> +        val content = binding.editTextSideEffect.text.toString()
여기도 CreateDailyRecord 부분과 동일하게 가면 될 것 같습니다!

2024-05-25 23:59 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createSideEffect/CreateSideEffectViewModel.kt
> +            if (!unExistAdverseEffectStateFlow.value) {
여기도 CreateDailyRecord와 동일한 내용입니다!

2024-05-26 04:28 UTC, dogmania commented on data/src/main/java/com/foregg/data/dto/dailyRecord/SideEffectResponseListItem.kt
> +data class SideEffectResponseListItem(
넵 수정했습니다!

2024-05-26 04:29 UTC, dogmania commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
> +            customTabBar.leftTab.setOnClickListener {
넵 수정했습니다!

2024-05-26 06:17 UTC, rudtjr1106 approved these changes
서버 주석처리 된 부분과 adapter 연결이 하나 빠진 것 같아 코멘트 남겼습니다! 해당 부분만 확인해주시고 merge하면 될 것 같습니다! 고생하셨습니다!!

2024-05-26 06:17 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
> +            customTabBar.leftBtnClicked { viewModel.updateTabType(DailyRecordTabType.ADVERSE_EFFECT) }
여기 부작용 adapter 연결이 사라졌습니다!

2024-05-26 06:17 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
> +//            viewModelScope.launch {
엇 여기 주석처리는 버그 때문인가용?

2024-05-26 06:34 UTC, merged