Feat: 정보 페이지 구현, 디자인 요구사항 반영, 홈 화면 팀 소개 배너 구현, 버그 사항 수정
FOREGG-DEV/FOREGG_Android pull request #65
Opened 2024-05-30 13:27 UTC by dogmania

close #63 

### 구현 사항

- 정보 페이지 구현
- 정부 지원금 상세 페이지 구현
- 하루기록 버튼 @android/transparent 적용
- 홈 화면 오늘의 일정 카드에서 진료 내용 기록하기 버튼이 잘리는 버그 수정
- 나의 챌린지가 존재하지 않을 때 보이지 않아야 하는 텍스트뷰가 보이는 버그 수정
- 나의 챌린지 요일 버튼 클릭을 통한 챌린지 완료 기능 구현
- 나의 챌린지 현재 주차의 성공 요일을 반영한 버튼 디자인 변경 로직 구현
- 홈 화면 팀 소개 배너 구현
- 홈 화면 오늘의 일정 카드의 stroke 기본값을 0dp로 설정 후 다가오는 일정에만 stroke를 부여하는 로직 구현

2024-05-30 14:58 UTC, rudtjr1106 requested changes
정보 관련 기획이 아직 확정되지 않아서 일단은 현재 디자인 기준으로 리뷰 남겼습니다!

2024-05-30 14:58 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeChallengeViewHolder.kt
> +            item.successDays?.let {list ->
요기 list에서 forEach 사용하시면 더 편하실겁니다!

```
item.successDays.forEach {
 if(it == today) ~~
}
```
요런식으로요!

2024-05-30 14:58 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeViewModel.kt
> +            ForeggLog.D(btnDayStateFlow.value.toString() + ", " + myChallengeListStateFlow.value[index].name)
여기 로그 들어가있습니다!

2024-05-30 14:58 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeViewModel.kt
> +                resultResponse(it, { getMyChallenge() }, null, true)
요거는 중요한 내용은 아니긴 한데
만약 필요 없는 값이 있다면 named argument를 사용하시면 됩니다!
이 함수를 예로 들자면 error를 따로 처리할 필요가 없다는 가정하에 
` resultResponse(it, { getMyChallenge() }, needLoading = true)`
요런식으로요!

2024-05-30 14:58 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationAdapter.kt
> +    internal class GridSpacingItemDecoration(
internal class으로 GridSpacingItemDecoration을 정의하는거 아주 좋은 것 같습니다! 지금은 아니지만 언젠가 사용할 수 있으니InformationAdapter 클래스 밖에서다가 정의하는 건 어떨까요??

2024-05-30 14:58 UTC, rudtjr1106 commented on presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationFragment.kt
> +
아직 임시로 제작된 페이지 이긴 하나 adapter를 4개로 관리하는 방법보다 해당 페이지에서는 2중첩 리사이클러뷰로 총 2개의 어뎁터로 관리하는게 좋을 것 같습니다..!

예로 들면 아래 사진이 recyclerView의 아이템으로 한다면
<img width="273" alt="image" src="https://github.com/FOREGG-DEV/FOREGG_Android/assets/83599356/35fb71ef-9471-4ee7-9521-dc9161044c1a">

위 아이템에서 아래 동그라미들을 아이템으로 갖는 recyclerView를 만드는 겁니다!
<img width="273" alt="image" src="https://github.com/FOREGG-DEV/FOREGG_Android/assets/83599356/63ff73cc-e9e5-4537-a410-0a2bc050db12">

좀 더 자세한 내용은 아래글을 참고하시면 이해하시기 편하실 겁니다!
https://notepad96.tistory.com/201

이렇게 제작한다면 서버에서 처리하든, 앱 자체에서 처리하든 item의 변화가 생겼을 때 viewModel에서만 코드를 수정하면 되기 때문에 유지보수성도 좋고, fragment에서 4개의 어뎁터를 1개로 줄일 수 있으니 코드의 간결성도 높아지게 됩니다!

2024-05-30 17:17 UTC, dogmania commented on presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeChallengeViewHolder.kt
> +            item.successDays?.let {list ->
네 수정했습니다!

2024-05-30 17:17 UTC, dogmania commented on presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeViewModel.kt
> +                resultResponse(it, { getMyChallenge() }, null, true)
네 수정했습니다!

2024-05-30 17:18 UTC, dogmania commented on presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationAdapter.kt
> +    internal class GridSpacingItemDecoration(
네 수정했습니다!

2024-05-30 17:18 UTC, dogmania commented on presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationFragment.kt
> +
네 수정했습니다!

2024-05-31 00:10 UTC, rudtjr1106 approved these changes
변경사항 모두 확인했습니다! 수고하셨습니다!

2024-05-31 03:26 UTC, merged